spring:
  application:
    name: spring-logging-example

  instance:
    id: ${spring.application.name}-${spring.profiles.active:default}-${random.uuid}

  datasource:
    url: jdbc:h2:mem:logging;DB_CLOSE_ON_EXIT=FALSE
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create


logstash:
  host: localhost
  port: 50000
